#!/usr/bin/env python3
"""Continuous completeness audit for the Symfony 8 Certification prep platform.

Regenerates specs/CoverageReport.md from the SAME syllabus data and evidence
checks as tools/gen_traceability_matrix.py (imported, not re-implemented) so
this report and specs/TraceabilityMatrix.md can never silently drift apart
and report two different coverage numbers for the same thing.

Run from the repo root:  python tools/audit.py
Exit code is non-zero if any Main Chapter path is missing outright (a harder
failure than "TO VERIFY" for a checklist item that IS present but incomplete).
See specs/AuditPolicy.md.
"""
from __future__ import annotations
import os, sys, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORT = os.path.join(ROOT, "specs", "CoverageReport.md")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_traceability_matrix import SYLLABUS, evidence, status_for, gaps  # noqa: E402


def audit():
    full, partial, missing = [], [], []
    for topic, subtopic, main, additional, note in SYLLABUS:
        label = f"{topic} → {subtopic}"
        if not main:
            missing.append((label, "—", "no Main Chapter mapped (see Anomaly in TraceabilityMatrix.md)"))
            continue
        ev = evidence(main)
        if not ev["path_exists"]:
            missing.append((label, main, "file missing"))
            continue
        status = status_for(ev, out_of_scope_dep=False)
        gap_list = gaps(ev, main)
        if status == "PASS":
            full.append((label, main))
        else:
            partial.append((label, main, "missing: " + ", ".join(gap_list)))
    return full, partial, missing


def write_report(full, partial, missing):
    n = len(full) + len(partial) + len(missing)
    pct = lambda x: f"{(100.0 * x / n):.1f}%" if n else "n/a"
    now = datetime.date.today().isoformat()
    lines = [
        "# Coverage Report",
        "",
        f"_Auto-generated by `tools/audit.py` on {now}, from the same syllabus data",
        "and evidence checks as `specs/TraceabilityMatrix.md` "
        "(`tools/gen_traceability_matrix.py`). Do not edit by hand._",
        "",
        "## Coverage Report",
        "",
        f"- **Total official syllabus subtopics:** {n} "
        "(excludes the Out-of-scope / Additional Learning section)",
        f"- **PASS — automated evidence complete:** {len(full)} ({pct(len(full))})",
        f"- **TO VERIFY — evidence incomplete:** {len(partial)} ({pct(len(partial))})",
        f"- **Missing (no file at all):** {len(missing)} ({pct(len(missing))})",
        "",
        "This is an automated-evidence count, not a claim of pedagogical",
        "completeness or of 100% syllabus alignment — see the Status legend in",
        "[TraceabilityMatrix.md](TraceabilityMatrix.md) for exactly what PASS",
        "does and does not certify.",
        "",
    ]
    if partial:
        lines += ["## ⚠ TO VERIFY — evidence incomplete", ""]
        lines += [f"- `{rel}` — {why} ({item})" for item, rel, why in partial] + [""]
    if missing:
        lines += ["## ❌ Missing", ""]
        lines += [f"- `{rel}` — {why} ({item})" for item, rel, why in missing] + [""]
    if not partial and not missing:
        lines += ["✅ Every official syllabus subtopic has complete automated evidence "
                  "(worked example, exercises, solutions, a situational quiz question, "
                  "certification traps, a Symfony 8.0 source reference, and an official "
                  "doc/php.net/RFC reference). This still does not mean 100% — see "
                  "TraceabilityMatrix.md for what this does and does not check.", ""]
    open(REPORT, "w", encoding="utf-8").write("\n".join(lines))
    return n


def main() -> int:
    full, partial, missing = audit()
    n = write_report(full, partial, missing)
    print(f"Syllabus subtopics: {n} | PASS: {len(full)} | TO VERIFY: {len(partial)} | missing: {len(missing)}")
    print(f"Report written to {os.path.relpath(REPORT, ROOT)}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
