#!/usr/bin/env python3
"""Continuous completeness audit for the Symfony 8 Certification prep platform.

Maps every syllabus micro-chapter to its file and checks the presence of the
mandatory building blocks (Official References, deep dive, diagram, traps,
exercises, exam-style questions). Regenerates specs/CoverageReport.md.

Run from the repo root:  python tools/audit.py
Exit code is non-zero if any syllabus chapter is missing or lacks references,
so it can gate CI.  See specs/AuditPolicy.md.
"""
from __future__ import annotations
import os, re, sys, glob, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
MATRIX = os.path.join(ROOT, "specs", "TraceabilityMatrix.md")
REPORT = os.path.join(ROOT, "specs", "CoverageReport.md")

CHECKS = {
    "references": re.compile(r"(?m)^#{2,4}\s+Official References\s*$"),
    "deep_dive":  re.compile(r"(?m)^#{2,4}\s+Deep Dive"),
    "diagram":    re.compile(r"```mermaid"),
    "traps":      re.compile(r"[Cc]ertification traps"),
    "exercises":  re.compile(r"(?m)^#{2,4}\s+Exercises"),
    "questions":  re.compile(r"[Cc]ertification questions"),
    "official_link": re.compile(r"symfony\.com/doc|php\.net"),
}


def syllabus_chapters() -> list[tuple[str, str]]:
    """(syllabus item, chapter path) parsed from the Traceability Matrix tables."""
    rows = []
    for line in open(MATRIX, encoding="utf-8"):
        m = re.match(r"\|\s*(.+?)\s*\|\s*`([^`]+\.md)`\s*\|", line)
        if m:
            rows.append((m.group(1), m.group(2)))
    return rows


def audit():
    rows = syllabus_chapters()
    full, partial, missing = [], [], []
    for item, rel in rows:
        path = os.path.join(DOCS, rel)
        if not os.path.exists(path):
            missing.append((item, rel, "file missing"))
            continue
        txt = open(path, encoding="utf-8").read()
        gaps = [name for name, pat in CHECKS.items() if not pat.search(txt)]
        # references + at least one official link are non-negotiable
        hard = [g for g in gaps if g in ("references", "official_link")]
        if hard:
            missing.append((item, rel, "no " + ", ".join(hard)))
        elif gaps:
            partial.append((item, rel, "missing: " + ", ".join(gaps)))
        else:
            full.append((item, rel))
    return rows, full, partial, missing


def write_report(rows, full, partial, missing):
    n = len(rows)
    pct = lambda x: f"{(100.0 * x / n):.1f}%" if n else "n/a"
    now = datetime.date.today().isoformat()
    lines = [
        "# Coverage Report",
        "",
        f"_Auto-generated by `tools/audit.py` on {now}. Do not edit by hand._",
        "",
        "## Coverage Report",
        "",
        f"- **Total syllabus items:** {n}",
        f"- **Covered (✔ full):** {len(full)} ({pct(len(full))})",
        f"- **Partially covered (⚠):** {len(partial)} ({pct(len(partial))})",
        f"- **Missing (❌):** {len(missing)} ({pct(len(missing))})",
        "",
    ]
    if partial:
        lines += ["## ⚠ Partially covered", ""]
        lines += [f"- `{rel}` — {why} ({item})" for item, rel, why in partial] + [""]
    if missing:
        lines += ["## ❌ Missing / incomplete", ""]
        lines += [f"- `{rel}` — {why} ({item})" for item, rel, why in missing] + [""]
    if not partial and not missing:
        lines += ["✅ **100% coverage** — every syllabus item maps to a chapter that "
                  "has Official References, a deep dive, a diagram, traps, exercises, "
                  "and exam-style questions.", ""]
    open(REPORT, "w", encoding="utf-8").write("\n".join(lines))
    return n, full, partial, missing


def main():
    rows, full, partial, missing = audit()
    n, *_ = write_report(rows, full, partial, missing)
    print(f"Syllabus items: {n} | full: {len(full)} | partial: {len(partial)} | missing: {len(missing)}")
    print(f"Report written to {os.path.relpath(REPORT, ROOT)}")
    # Hard-fail only on missing references/files; partial (soft gaps) is a warning.
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
