#!/usr/bin/env python3
"""Continuous completeness audit for the Symfony 8 Certification prep platform.

Regenerates specs/CoverageReport.md from the SAME syllabus data and evidence
checks as tools/gen_traceability_matrix.py (imported, not re-implemented) so
this report and specs/TraceabilityMatrix.md can never silently drift apart
and report two different coverage numbers for the same thing.

Since P0-04, this uses the six-status schema (absent / structure / partiel /
validé techniquement / validé éditorialement / conforme) — see
gen_traceability_matrix.py's multi_status() docstring for exactly what each
status does and does not claim. This report never uses the word "conforme"
or "PASS" as a synonym for "certified" or "syllabus-confirmed"; see
specs/OfficialSyllabusBaseline.md for the network-reachability limits this
count is subject to.

Run from the repo root:  python tools/audit.py
Exit code is non-zero if any Main Chapter path is missing outright ("absent"
with no file on disk — a harder failure than an incomplete-but-present
chapter). See specs/AuditPolicy.md.
"""
from __future__ import annotations
import os, sys, datetime, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORT = os.path.join(ROOT, "specs", "CoverageReport.md")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_traceability_matrix import SYLLABUS, evidence, multi_status, multi_gaps  # noqa: E402

ORDER = ["conforme", "validé éditorialement", "validé techniquement", "partiel", "structure", "absent"]


def audit():
    rows = []  # (label, main, overall_status, gap_list)
    for topic, subtopic, main, additional, note in SYLLABUS:
        label = f"{topic} → {subtopic}"
        ev = evidence(main)
        ms = multi_status(ev, main, out_of_scope_dep=False)
        gap_list = multi_gaps(ev, main, ms)
        rows.append((label, main or "—", ms["overall"], gap_list))
    return rows


def write_report(rows):
    from repo_meta import stamp_line
    n = len(rows)
    counts = collections.Counter(r[2] for r in rows)
    pct = lambda x: f"{(100.0 * x / n):.1f}%" if n else "n/a"
    now = datetime.date.today().isoformat()
    lines = [
        "# Coverage Report",
        "",
        stamp_line("tools/audit.py"),
        "",
        f"_Auto-generated by `tools/audit.py` on {now}, from the same syllabus data",
        "and evidence checks as `specs/TraceabilityMatrix.md` "
        "(`tools/gen_traceability_matrix.py`). Do not edit by hand._",
        "",
        "## Coverage Report — six-status schema",
        "",
        f"- **Total subtopics tracked:** {n} (this repo's own working taxonomy —",
        "  see `specs/OfficialSyllabusBaseline.md` §1; **not** independently",
        "  re-verified against the live syllabus page this run — network egress",
        "  to `certification.symfony.com`/`symfony.com` is blocked in this",
        "  environment)",
    ]
    for s in ORDER:
        lines.append(f"- **{s}:** {counts[s]} ({pct(counts[s])})")
    lines += [
        "",
        "This is an automated-evidence count, not a claim of pedagogical",
        "completeness, official-syllabus confirmation, or 100% alignment — see the",
        "six-status legend in [TraceabilityMatrix.md](TraceabilityMatrix.md) for",
        "exactly what each status does and does not certify. `conforme` requires,",
        "among other things, a French translation to exist for the chapter — it is",
        "a stricter bar than the previous single `PASS` status, by design (P0-04).",
        "",
    ]
    incomplete = [r for r in rows if r[2] != "conforme"]
    if incomplete:
        lines += ["## Subtopics not yet `conforme`", ""]
        for label, main, status, gap_list in incomplete:
            why = "; ".join(gap_list) if gap_list else "—"
            lines.append(f"- `{main}` — **{status}** — {why} ({label})")
        lines.append("")
    else:
        lines += ["✅ Every tracked subtopic reaches `conforme` under this repo's own",
                  "automated-evidence proxies. This still does not mean the official",
                  "syllabus has been re-verified live, or that a human has approved",
                  "every chapter — see TraceabilityMatrix.md for what this does and",
                  "does not check.", ""]
    open(REPORT, "w", encoding="utf-8").write("\n".join(lines))
    return n


def main() -> int:
    rows = audit()
    n = write_report(rows)
    counts = collections.Counter(r[2] for r in rows)
    absent_on_disk = sum(1 for _, main, status, _ in rows if status == "absent" and main != "—")
    summary = " | ".join(f"{s}: {counts[s]}" for s in ORDER)
    print(f"Subtopics: {n} | {summary}")
    print(f"Report written to {os.path.relpath(REPORT, ROOT)}")
    # Hard failure only when a Main Chapter is mapped but genuinely missing from
    # disk - a harder problem than "present but evidence incomplete".
    return 1 if absent_on_disk else 0


if __name__ == "__main__":
    sys.exit(main())
