#!/usr/bin/env python3
"""Flag auto-generated reports whose provenance stamp names a commit other
than the current HEAD (P1-04 / P1-05).

Every report `tools/repo_meta.py`-stamped report says which commit it was
generated from. This script does the honest, mechanical half of "flag
reports whose commit differs from the audited commit as stale": it does
NOT try to guess whether the drift matters (that needs a human or a
source-glob heuristic this script deliberately doesn't fake) — it just
tells you, per report, whether its stamped commit equals the repo's
current HEAD, and prints the stamped commit so you can diff it yourself.

This is expected to report every stamped file as "stale" immediately
after the commit that updated them is made (the stamp necessarily names
the *parent* commit, since the commit embedding the stamp doesn't exist
yet at generation time) — that one-commit lag is normal, not a defect.
Treat "stale" as "re-run the generator before trusting this file", not as
an automatic failure.

Run: python tools/check_report_freshness.py [--strict]
  --strict: exit 1 if any stamped report is stale (off by default — this
            check is informational unless the caller opts in, since the
            one-commit lag above is expected after every commit).
"""
from __future__ import annotations
import argparse, glob, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STAMP_RE = re.compile(r"_Generated by `([^`]+)` on (\d{4}-\d{2}-\d{2}), branch `([^`]*)`, commit `([0-9a-f]{7,40})`")


def current_head() -> str | None:
    try:
        out = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT,
                              capture_output=True, text=True, timeout=10)
        return out.stdout.strip()[:7] if out.returncode == 0 else None
    except Exception:
        return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--strict", action="store_true")
    args = ap.parse_args()

    head = current_head()
    if not head:
        print("check_report_freshness: could not determine current HEAD "
              "(git unavailable or not a repo) — cannot check freshness, "
              "not fabricating a result.")
        return 0

    stamped, unstamped = [], []
    for path in sorted(glob.glob(os.path.join(ROOT, "specs", "*.md"))):
        text = open(path, encoding="utf-8").read()
        m = STAMP_RE.search(text)
        rel = os.path.relpath(path, ROOT)
        if m:
            tool, date, branch, commit = m.groups()
            stamped.append((rel, tool, date, commit))
        else:
            unstamped.append(rel)

    print(f"check_report_freshness: current HEAD = {head}")
    print(f"{len(stamped)} report(s) carry a repo_meta.py provenance stamp:")
    stale = []
    for rel, tool, date, commit in stamped:
        status = "FRESH (matches HEAD)" if commit == head else f"STALE (stamped {commit} != HEAD {head})"
        if commit != head:
            stale.append(rel)
        print(f"  {rel}: generated {date} by {tool} from commit {commit} -> {status}")

    if unstamped:
        print(f"\n{len(unstamped)} specs/*.md file(s) have no repo_meta.py stamp "
              "(hand-authored narrative docs, not machine-regenerated reports, "
              "or predate this check — not necessarily a problem):")
        for rel in unstamped:
            print(f"  {rel}")

    print(f"\n{len(stale)}/{len(stamped)} stamped report(s) are stale relative to "
          "current HEAD. This is EXPECTED for one commit right after a report is "
          "committed (the stamp names the parent commit); re-run the relevant "
          "generator before trusting a report whose stale-ness predates the last "
          "commit by more than that.")

    if args.strict and stale:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
