#!/usr/bin/env python3
"""Final quality audit: per-chapter presence of required pedagogical sections,
syllabus coverage, and question-bank stats. Writes specs/FinalAudit.md.
Run: python tools/final_audit.py
"""
from __future__ import annotations
import os, re, glob, yaml, datetime, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
MATRIX = os.path.join(ROOT, "specs", "TraceabilityMatrix.md")

CHECKS = {
    # `## How it works internally` is what the four-file journey calls the same
    # section, so both spellings count — the audit tracks whether a chapter goes
    # under the hood, not which of two headings it puts that under.
    "Deep Dive":        re.compile(r"(?m)^#{2,4}\s+(Deep Dive|How it works internally)"),
    "Quick Revision":   re.compile(r"In a nutshell"),
    "Final Revision":   re.compile(r"(?m)^#{2,4}\s+Last-minute revision"),
    "Analogy":          re.compile(r"Real-world analogy"),
    "Exercises":        re.compile(r"(?m)^#{2,4}\s+Exercises"),
    "Questions":        re.compile(r"[Cc]ertification questions"),
    "Traps":            re.compile(r"[Cc]ertification traps"),
    "References":       re.compile(r"(?m)^#{2,4}\s+Official References"),
    "Mermaid":          re.compile(r"```mermaid"),
    "Related links":    re.compile(r"(?m)^<small>.*Related|Related:"),
    "Connections":      re.compile(r"(?m)^#{2,4}\s+Connections"),
    "Confidence check": re.compile(r"[Cc]onfidence"),
}

# Two sections no longer live in the lesson once a topic has been split into the
# four-file learning journey: the questions moved to `<topic>-exam.md` and the
# practice to `<topic>-exercises.md`. Searching only the lesson would report a
# false regression — the content did not disappear, it moved one file over — so
# these markers are resolved against the lesson *and* its journey siblings.
#
# The sibling carries the content in its own form, not under the lesson's old
# heading, so each migrated marker needs its own pattern there: an exam file is
# made of `??? question` blocks, an exercises file of `## Exercise N` headings.
MIGRATED = {
    "Questions": ("-exam.md", re.compile(r"(?m)^\?\?\?\s+question\b")),
    "Exercises": ("-exercises.md", re.compile(r"(?m)^#{2,4}\s+Exercise\s+\d")),
}


def satisfied_by_sibling(path: str, name: str) -> bool:
    """True when a migrated section now lives in this chapter's journey sibling."""
    suffix, pattern = MIGRATED[name]
    sibling = (path[:-3] if path.endswith(".md") else path) + suffix
    if not os.path.exists(sibling):
        return False
    return bool(pattern.search(open(sibling, encoding="utf-8").read()))


def syllabus_chapters():
    rows = []
    for line in open(MATRIX, encoding="utf-8"):
        m = re.match(r"\|\s*(.+?)\s*\|\s*`([^`]+\.md)`\s*\|", line)
        if m:
            rows.append((m.group(1), m.group(2)))
    return rows

def bank_stats():
    total = 0; by_type = collections.Counter(); by_diff = collections.Counter()
    for f in glob.glob(os.path.join(ROOT, "quiz", "*.yml")):
        for c in (yaml.safe_load(open(f, encoding="utf-8")) or {}).get("categories", []):
            for q in c.get("questions", []):
                total += 1
                if q.get("type"): by_type[q["type"]] += 1
                if q.get("difficulty"): by_diff[q["difficulty"]] += 1
    return total, by_type, by_diff

def main():
    rows = syllabus_chapters()
    results = {}
    per_check = collections.Counter()
    for item, rel in rows:
        p = os.path.join(DOCS, rel)
        txt = open(p, encoding="utf-8").read() if os.path.exists(p) else ""
        got = {name: bool(pat.search(txt)) or
                     (name in MIGRATED and satisfied_by_sibling(p, name))
               for name, pat in CHECKS.items()}
        results[rel] = got
        for name, ok in got.items():
            if ok: per_check[name] += 1
    n = len(rows)
    total, by_type, by_diff = bank_stats()
    now = datetime.date.today().isoformat()

    from repo_meta import stamp_line
    L = [f"# Final Quality Audit", "",
         stamp_line("tools/final_audit.py"), "",
         f"_Auto-generated by `tools/final_audit.py` on {now}._", "",
         "## Syllabus coverage", "",
         f"- Chapters (syllabus items) found in `specs/TraceabilityMatrix.md`: **{n}**"
         " (parsed live from the matrix's own rows every run — never a hardcoded total;"
         " see `specs/TraceabilityMatrix.md`'s own Coverage summary for the six-status"
         " (absent/structure/partiel/validé techniquement/validé éditorialement/conforme)"
         " breakdown — this count is this repo's own tracked total, not an independently"
         " re-verified official figure)",
         f"- Question bank: **{total}** questions",
         f"  - by type: {dict(by_type)}",
         f"  - by difficulty: {dict(by_diff)}", "",
         "## Section presence across chapters", "",
         "| Section | Chapters with it | % |", "|---|---|---|"]
    for name in CHECKS:
        c = per_check[name]
        L.append(f"| {name} | {c}/{n} | {100*c//n}% |")
    # list gaps for the "should be everywhere" sections
    universal = ["Deep Dive", "Quick Revision", "Final Revision", "References", "Questions"]
    L += ["", "## Gaps (universal sections missing)", ""]
    any_gap = False
    for name in universal:
        missing = [rel for rel, g in results.items() if not g[name]]
        if missing:
            any_gap = True
            L.append(f"- **{name}** missing in {len(missing)}: {', '.join(missing[:8])}"
                     + (" …" if len(missing) > 8 else ""))
    if not any_gap:
        L.append("None — every chapter has Deep Dive, Quick + Final Revision, References, and Questions. ✅")
    open(os.path.join(ROOT, "specs", "FinalAudit.md"), "w", encoding="utf-8").write("\n".join(L)+"\n")
    print("\n".join(L[:30]))
    print("... report written to specs/FinalAudit.md")

if __name__ == "__main__":
    main()
