#!/usr/bin/env python3
"""Run every generator, or prove the committed artefacts match what they produce.

Generated pages live in the repository alongside hand-written ones, so they can
drift: someone edits a lesson's `## Key takeaways`, the revision sheet keeps the
old text, and nothing notices until a reader does. `--check` closes that by making
drift a build failure.

    python3 tools/gen_all.py            # regenerate in place
    python3 tools/gen_all.py --check    # fail if the committed files differ

`--check` copies the tree to a temporary directory, regenerates there, and diffs
against what is committed. It never writes to the working tree, so it is safe in
CI and safe to run on a dirty checkout.

Exit status: 0 when everything matches, 1 otherwise — with the differing files
named, because "something is stale" is not an actionable message.
"""
from __future__ import annotations

import argparse
import filecmp
import os
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Order matters: quiz JSON is built from the bank, and the chapter exams and
# flashcards are what the mock exam samples from.
GENERATORS = [
    "gen_quiz_json.py",
    "gen_chapter_exams.py",
    "gen_flashcards.py",
    "gen_revision_sheets.py",
    "gen_traceability_matrix.py",
    "mock_exam.py",
]

# Directories a generator may write into. Only these are compared, so an unrelated
# edit elsewhere in the tree never shows up as generator drift.
OUTPUT_DIRS = [
    os.path.join("docs", "exams"),
    os.path.join("docs", "revision"),
    os.path.join("docs", "assets", "quiz-data.json"),
    os.path.join("specs", "TraceabilityMatrix.md"),
    os.path.join("quiz", "flashcards.csv"),
]


def run_generators(root: str) -> int:
    env = dict(os.environ, PYTHONPATH=os.path.join(root, "tools"))
    for gen in GENERATORS:
        path = os.path.join(root, "tools", gen)
        if not os.path.exists(path):
            continue
        proc = subprocess.run([sys.executable, path], cwd=root, env=env,
                              capture_output=True, text=True)
        if proc.returncode != 0:
            print(f"gen_all: FAIL — {gen} exited {proc.returncode}", file=sys.stderr)
            print((proc.stdout + proc.stderr).strip()[-3000:], file=sys.stderr)
            return 1
    return 0


# Some reports stamp themselves with the generating date and commit, so they can
# never be byte-identical across two runs. That provenance is deliberate, not drift:
# blank it on both sides so the comparison is about content.
# The whole provenance line goes, not just the date: `--check` regenerates in a copy
# with no .git, so branch and commit legitimately read "unknown" there. Comparing
# provenance across two different checkouts is meaningless; comparing content is not.
_STAMP = re.compile(rb"(?m)^_?Generated by .*$|\d{4}-\d{2}-\d{2}"
                    rb"|commit `[0-9a-f]{7,40}`")


def _normalised(path: str) -> bytes:
    with open(path, "rb") as fh:
        return _STAMP.sub(b"", fh.read())


def _same(a: str, b: str) -> bool:
    """True when two artefacts match once their provenance stamps are ignored."""
    if filecmp.cmp(a, b, shallow=False):
        return True
    return _normalised(a) == _normalised(b)


def _walk(base: str, rel: str):
    """Every file under `rel`, whether `rel` is a directory or a single file."""
    full = os.path.join(base, rel)
    if os.path.isfile(full):
        yield rel
        return
    for dirpath, dirnames, filenames in os.walk(full):
        dirnames[:] = [d for d in dirnames if d != ".git"]
        for fn in sorted(filenames):
            yield os.path.relpath(os.path.join(dirpath, fn), base)


def check() -> int:
    with tempfile.TemporaryDirectory(prefix="gen-all-") as tmp:
        work = os.path.join(tmp, "repo")
        shutil.copytree(
            ROOT, work,
            ignore=shutil.ignore_patterns(".git", "site", "node_modules",
                                          "__pycache__", ".venv", "venv"),
        )
        if run_generators(work) != 0:
            return 1

        differing, missing = [], []
        for rel in OUTPUT_DIRS:
            for f in _walk(work, rel):
                committed, regenerated = os.path.join(ROOT, f), os.path.join(work, f)
                if not os.path.exists(committed):
                    missing.append(f)
                elif not _same(committed, regenerated):
                    differing.append(f)

        if not differing and not missing:
            print("gen_all: OK — every generated artefact matches its committed version.")
            return 0

        print("gen_all: FAIL — generated artefacts differ from what is committed.",
              file=sys.stderr)
        for f in sorted(missing):
            print(f"  missing (generator produces it, repo does not have it): {f}",
                  file=sys.stderr)
        for f in sorted(differing):
            print(f"  stale: {f}", file=sys.stderr)
        print("\n  fix: python3 tools/gen_all.py && git add -A", file=sys.stderr)
        return 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="do not write; fail if committed artefacts are stale")
    args = ap.parse_args()

    if args.check:
        return check()

    rc = run_generators(ROOT)
    if rc == 0:
        print(f"gen_all: OK — ran {len(GENERATORS)} generator(s).")
    return rc


if __name__ == "__main__":
    sys.exit(main())
