#!/usr/bin/env python3
"""Shared provenance stamp for auto-generated reports (P1-04).

Every report this repo auto-generates should say, verifiably: what commit
it was generated from, whether the working tree was clean at that moment,
what date/time, and what tool versions were in play — so a reader (or
`tools/check_report_freshness.py`, P1-05) can tell a report apart from a
stale one without re-running anything.

This module does not fabricate anything it can't check: if `git` isn't
available or the call fails, the stamp says so explicitly instead of
inventing a commit hash.
"""
from __future__ import annotations
import datetime
import platform
import subprocess


def _run(cmd: list[str]) -> str | None:
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
        if out.returncode != 0:
            return None
        return out.stdout.strip()
    except Exception:
        return None


def git_stamp() -> dict:
    """Return {commit, short_commit, branch, dirty, date} — any field that
    can't actually be determined is None, never guessed."""
    commit = _run(["git", "rev-parse", "HEAD"])
    short_commit = commit[:7] if commit else None
    branch = _run(["git", "rev-parse", "--abbrev-ref", "HEAD"])
    status = _run(["git", "status", "--porcelain"])
    dirty = bool(status) if status is not None else None
    return {
        "commit": commit,
        "short_commit": short_commit,
        "branch": branch,
        "dirty": dirty,
        "date": datetime.date.today().isoformat(),
    }


def stamp_line(tool: str) -> str:
    """One Markdown line documenting exactly what generated a report and
    from what repo state, for reproducibility (P1-04). `tool` is the
    generating script's path, e.g. 'tools/gen_traceability_matrix.py'."""
    s = git_stamp()
    commit_part = (
        f"commit `{s['short_commit']}`" if s["short_commit"] else
        "commit **unknown (`git rev-parse` failed — not fabricated)**"
    )
    branch_part = f"branch `{s['branch']}`" if s["branch"] else "branch unknown"
    if s["dirty"] is True:
        dirty_part = "**working tree had uncommitted changes at generation time**"
    elif s["dirty"] is False:
        dirty_part = "working tree clean at generation time"
    else:
        dirty_part = "working-tree cleanliness unknown (`git status` failed)"
    py = platform.python_version()
    return (
        f"_Generated by `{tool}` on {s['date']}, {branch_part}, {commit_part} "
        f"({dirty_part}), Python {py}. Re-run the tool to refresh; "
        f"`tools/check_report_freshness.py` flags this report as stale once "
        f"the repo's HEAD moves past the commit above._"
    )


if __name__ == "__main__":
    print(stamp_line("tools/repo_meta.py (self-test)"))
